import {createReviewService} from '../src/service.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {checked} from '../src/process.mjs';import {captureSnapshot} from '../src/snapshot.mjs';import {createRetrievalScope} from '../src/retrieval-scope.mjs';
test('automatic old-only deleted dependency reuses selected original old identity without restoring excluded deletions',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-auto-old-'));t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-auto-old-'));await rm(root,{recursive:true,force:true});});const git=(...args)=>checked('git',args,{cwd:root});await git('init');await git('config','user.name','test');await git('config','user.email','test@example.com');await writeFile(path.join(root,'main.ts'),'import x from "./helper";\n');await writeFile(path.join(root,'helper.ts'),'export default 1;\n');await writeFile(path.join(root,'context.txt'),'APPROVED');await git('add','.');await git('commit','-qm','base');await git('rm','helper.ts');await writeFile(path.join(root,'main.ts'),'export default 2;\n');await git('commit','-qam','target');await writeFile(path.join(root,'helper.ts'),'WORKTREE_SECRET');const status=await git('status','--porcelain');
 const selected=await captureSnapshot(root,{commit:'HEAD',autoContext:true});const c=selected.autoContext.candidates.find(x=>x.path==='helper.ts');assert.deepEqual(c.sourceSides,['old']);assert.equal(c.status,'reused-changed-old');assert.equal(selected.context.length,0);const scope=createRetrievalScope(selected),helper=selected.files.find(f=>f.path==='helper.ts'),sources=scope.catalog().filter(x=>x.path==='helper.ts');assert.equal(sources.filter(x=>x.side==='old').length,1);assert.equal(sources[0].fileId,helper.id);assert.equal(scope.read({id:sources.find(x=>x.side==='old').id,start:1,count:1}).text,'export default 1;\n');
 const exec={agent:{session:{header:{cwd:root}},options:{provider:'test',model:'model'}},signal:new AbortController().signal};let reads=0;const service=createReviewService({async *stream(req){const p=JSON.parse(req.messages[0].content[0].text);let result;if(p.file?.path==='main.ts'&&!p.retrieved.length)result={requests:[{kind:'read',id:p.catalog.find(x=>x.path==='helper.ts'&&x.side==='old').id,start:1,count:1}]};else{if(p.file?.path==='main.ts'){reads++;assert.equal(p.retrieved[0].result.text,'export default 1;\n');assert.ok(!p.catalog.some(x=>x.path==='helper.ts'&&x.side==='context-old'));}result={findings:[],limitations:[]};}yield {type:'text-delta',text:JSON.stringify(result)};yield {type:'finish',reason:{kind:'stop'}};}},{allowModelSending:true,authorize:async()=>true});const preview=await service.preview({commit:'HEAD',autoContext:true},exec);assert.equal(preview.autoContext.candidates.find(x=>x.path==='helper.ts').status,'reused-changed-old');assert.deepEqual(preview.contextPaths,[]);const review=await service.execute({previewId:preview.previewId,confirmed:true},exec);assert.equal(reads,1);assert.equal(review.report.outdated,false);assert.equal(review.report.coverage.completed,2);assert.equal(review.report.modelCalls,4);assert.equal(review.report.autoContext.candidates.find(x=>x.path==='helper.ts').status,'reused-changed-old');service.dispose();
 const full=await captureSnapshot(root,{commit:'HEAD',autoContext:true,contextPaths:['context.txt'],maxContextFiles:1});assert.equal(full.context.length,1);assert.equal(full.autoContext.candidates.find(x=>x.path==='helper.ts').status,'reused-changed-old');
 const explicit=await captureSnapshot(root,{commit:'HEAD',autoContext:true,oldContextPaths:['helper.ts']});assert.equal(explicit.context.length,0);assert.ok(!explicit.autoContext.candidates.some(x=>x.path==='helper.ts'));
 await assert.rejects(captureSnapshot(root,{commit:'HEAD',autoContext:true,maxSnapshotBytes:100}),/limit/);
 const excluded=await captureSnapshot(root,{commit:'HEAD',autoContext:true,selectedPaths:['main.ts']});assert.equal(excluded.autoContext.candidates.find(x=>x.path==='helper.ts').status,'blocked');assert.equal(excluded.context.length,0);assert.ok(!JSON.stringify(excluded).includes('export default 1'));assert.ok(!JSON.stringify(selected).includes('WORKTREE_SECRET'));assert.equal(selected.id,(await captureSnapshot(root,{commit:'HEAD',autoContext:true})).id);assert.deepEqual(await git('status','--porcelain'),status);
});
