import {createReviewService} from '../src/service.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {validateBusinessGroups,prepareBusinessGroups,BUSINESS_GROUP_INSTRUCTIONS} from '../src/business-groups.mjs';
import {buildCoveragePlan} from '../src/coverage-plan.mjs';
import {reviewSnapshot} from '../src/review.mjs';
test('enabled service previews grouping and executes plan main plus combined task without extra approval',async()=>{const calls=[];const service=createReviewService({async *stream(r){calls.push(r.system);const body=r.system.includes('按共同业务契约')?{groups:[{fileIds:['a','b'],reason:'contract'}]}:r.system.includes('仅制定审查计划')?{risks:[]}:{findings:[],limitations:[]};yield {type:'text-delta',text:JSON.stringify(body)};yield {type:'finish',reason:{kind:'stop'}};}},{capture:async()=>({id:'s',root:'/repo',vcs:'git',files:files(),context:[]}),allowModelSending:true,authorize:async()=>true,enableBusinessGrouping:true,enableRiskPlanning:true});const exec={agent:{session:{header:{cwd:'/repo'}},options:{provider:'offline',model:'none'}},signal:new AbortController().signal};const p=await service.preview({},exec);assert.equal(calls.length,0);assert.equal(p.plan.minimumCalls,5);const r=await service.execute({previewId:p.previewId,confirmed:true},exec);assert.equal(calls.length,7);assert.equal(r.report.businessGrouping.status,'completed');assert.equal(r.report.interactions[0].status,'completed');service.dispose();});
test('grouping failure retains approved primary coverage and never restores excluded files',async()=>{
 const selected=[...files(),{id:'excluded',path:'excluded.cpp',eligibility:'excluded'}];let calls=0;
 const r=await reviewSnapshot({id:'s',vcs:'git',files:selected,context:[]},async req=>{calls++;if(req.instructions===BUSINESS_GROUP_INSTRUCTIONS)return {groups:[{fileIds:['a','excluded'],reason:'invalid'}]};return {findings:[],limitations:[]};},{enableRetrieval:true,enableBusinessGrouping:true});
 assert.equal(calls,3);assert.equal(r.businessGrouping.status,'fallback');assert.equal(r.status,'partial');assert.deepEqual(r.files.map(f=>f.status),['completed','completed','excluded']);assert.equal(r.interactions.length,0);
});
test('single-file grouping is zero-call skip and grouping budget cannot manufacture completed primaries',async()=>{
 const s={id:'s',vcs:'git',files:files(),context:[]};const one=await reviewSnapshot({...s,files:[s.files[0]]},()=>({findings:[],limitations:[]}),{enableRetrieval:true,enableBusinessGrouping:true});assert.equal(one.modelCalls,1);assert.equal(one.businessGrouping,undefined);
 const limited=await reviewSnapshot(s,()=>({groups:[{fileIds:['a','b'],reason:'contract'}]}),{enableRetrieval:true,enableBusinessGrouping:true,maxCalls:1});assert.equal(limited.modelCalls,1);assert.ok(limited.files.every(f=>f.status!=='completed'));assert.equal(limited.status,'failed');
});
const files=()=>['a','b'].map(id=>({id,path:id+'.cpp',eligibility:'reviewable',properties:[],left:{text:'old'},right:{text:'new'}}));
test('preview counts grouping once but discloses dynamic interactions without retaining source',()=>{const plan=buildCoveragePlan({id:'s',files:files()},{instructions:'review',maxInputBytes:96000,enableBusinessGrouping:true,enableRiskPlanning:true});assert.equal(plan.minimumCalls,5);assert.equal(plan.businessGrouping.dynamicInteractionCalls,'unknown-until-execution');assert.equal(plan.businessGrouping.maximumAdditionalInitialCalls,2);assert.ok(!JSON.stringify(plan).includes('old'));});
test('business grouping covers approved files exactly once and metadata contains no source',()=>{assert.ok(!prepareBusinessGroups(files()).includes('old'));assert.equal(validateBusinessGroups({groups:[{fileIds:['a','b'],reason:'contract'}]},files()).groups[0].confidence,'model-hypothesis');for(const ids of [['a'],['a','a'],['a','outside']])assert.throws(()=>validateBusinessGroups({groups:[{fileIds:ids,reason:'r'}]},files()));});
test('business tasks reach interaction pipeline inside first-primary shared lifecycle',async()=>{let signal;const r=await reviewSnapshot({id:'s',vcs:'git',files:files(),context:[]},async req=>{if(req.instructions===BUSINESS_GROUP_INSTRUCTIONS){signal=req.signal;return {groups:[{fileIds:['a','b'],reason:'shared contract'}]};}const input=JSON.parse(req.input);if(input.file?.id==='a')assert.equal(req.signal,signal);return {findings:[],limitations:[]};},{enableRetrieval:true,enableBusinessGrouping:true});assert.equal(r.businessGrouping.status,'completed');assert.equal(r.interactions.length,1);assert.equal(r.interactions[0].status,'completed');assert.equal(r.modelCalls,4);});
