import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {checked} from '../src/process.mjs';
import {createReviewService} from '../src/service.mjs';
test('real service caller preview zero-send execution report and negative change invalidation',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-caller-service-'));
 t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-caller-service-'));await rm(root,{recursive:true,force:true});});
 const git=(...args)=>checked('git',args,{cwd:root});await git('init');await git('config','user.name','Test');await git('config','user.email','test@example.invalid');
 await mkdir(path.join(root,'app'));await mkdir(path.join(root,'src'));
 await writeFile(path.join(root,'src','dep.ts'),'export const x=1;');
 await writeFile(path.join(root,'app','a.ts'),"import x from '../src/dep.ts';");
 await writeFile(path.join(root,'app','b.ts'),'NEGATIVE_BODY_DO_NOT_SEND');
 await git('add','.');await git('commit','-m','base');await writeFile(path.join(root,'src','dep.ts'),'export const x=2;');
 let calls=0;
 const service=createReviewService({async *stream(request){calls++;assert.ok(!JSON.stringify(request).includes('NEGATIVE_BODY_DO_NOT_SEND'));yield {type:'text-delta',text:'{"findings":[],"limitations":[]}'};yield {type:'finish',reason:{kind:'stop'}};}},{allowModelSending:true,authorize:async()=>true});
 t.after(()=>service.dispose());
 const exec={agent:{session:{header:{cwd:root}},options:{provider:'test',model:'test'}},signal:new AbortController().signal};
 const args={selectedPaths:['src/dep.ts'],callerScopePaths:['app']};
 const preview=await service.preview(args,exec);
 assert.equal(calls,0);assert.deepEqual(preview.contextPaths,['app/a.ts']);assert.match(preview.notice,/非匹配正文不发送/);
 assert.ok(!JSON.stringify(preview).includes('NEGATIVE_BODY_DO_NOT_SEND'));
 const result=await service.execute({previewId:preview.previewId,confirmed:true},exec);
 assert.ok(calls>0);assert.equal(result.report.status,'partial');assert.equal(result.report.callerDiscovery.scanned.length,2);assert.match(result.markdown,/不证明函数调用/);assert.equal(result.report.outdated,false);
 const stale=await service.preview(args,exec);const before=calls;
 await writeFile(path.join(root,'app','b.ts'),'NEW_NEGATIVE_BODY');
 await assert.rejects(service.execute({previewId:stale.previewId,confirmed:true},exec),/Files changed/);assert.equal(calls,before);
 await assert.rejects(service.preview({...args,callerScopePaths:['.']},exec),/Unsafe/);
});
