import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {checked} from '../src/process.mjs';
import {captureSnapshot} from '../src/snapshot.mjs';
test('working snapshot binds caller negative hashes and shares explicit context slots',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-caller-snapshot-'));
 t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-caller-snapshot-'));await rm(root,{recursive:true,force:true});});
 const git=(...args)=>checked('git',args,{cwd:root});await git('init');await git('config','user.email','test@example.invalid');await git('config','user.name','test');
 await mkdir(path.join(root,'src'));await mkdir(path.join(root,'app'));
 await writeFile(path.join(root,'src','dep.ts'),'export const x=1;');
 await writeFile(path.join(root,'app','a.ts'),"import x from '../src/dep.ts';");
 await writeFile(path.join(root,'app','b.ts'),'const unrelated=1;');
 await git('add','.');await git('commit','-m','base');
 await writeFile(path.join(root,'src','dep.ts'),'export const x=2;');
 const options={selectedPaths:['src/dep.ts'],callerScopePaths:['app']};
 const first=await captureSnapshot(root,options);
 assert.deepEqual(first.context.map(c=>c.path),['app/a.ts']);
 assert.equal(first.callerDiscovery.candidates[0].status,'captured');
 assert.equal(first.callerDiscovery.candidates[0].reason,'literal-relative-import');
 assert.equal(first.id,(await captureSnapshot(root,options)).id);
 await writeFile(path.join(root,'app','b.ts'),'const unrelated=2;');
 assert.notEqual(first.id,(await captureSnapshot(root,options)).id);
 await writeFile(path.join(root,'app','b.ts'),'const unrelated=1;');
 const limited=await captureSnapshot(root,{...options,contextPaths:['app/b.ts'],maxContextFiles:1});
 assert.deepEqual(limited.context.map(c=>c.path),['app/b.ts']);
 assert.equal(limited.callerDiscovery.candidates[0].status,'blocked');
 assert.match(limited.callerDiscovery.candidates[0].captureReason,/limit/);
 const historical=await captureSnapshot(root,{...options,commit:'HEAD'});assert.ok(historical.callerDiscovery);assert.equal(historical.callerDiscovery.history.target,historical.history.target);
});
