import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {checked} from '../src/process.mjs';
import {captureSnapshot} from '../src/snapshot.mjs';
import {createRetrievalScope} from '../src/retrieval-scope.mjs';
async function repo(t){const root=await mkdtemp(path.join(os.tmpdir(),'dsh-history-boundary-'));t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-history-boundary-'));await rm(root,{recursive:true,force:true});});const git=(...args)=>checked('git',args,{cwd:root});await git('init');await git('config','user.name','test');await git('config','user.email','test@example.com');return {root,git};}
test('binary deleted old dependency stays blocked without restoration or retrieval authority',async t=>{const {root,git}=await repo(t);await writeFile(path.join(root,'main.ts'),'import x from "./helper";\n');await writeFile(path.join(root,'helper.ts'),Buffer.from([0,1,2,3]));await git('add','.');await git('commit','-qm','base');await git('rm','helper.ts');await writeFile(path.join(root,'main.ts'),'export default 2;\n');await git('commit','-qam','target');const s=await captureSnapshot(root,{commit:'HEAD',autoContext:true});assert.equal(s.files.find(f=>f.path==='helper.ts').eligibility,'blocked');assert.equal(s.autoContext.candidates.find(c=>c.path==='helper.ts').status,'blocked');assert.deepEqual(s.context,[]);assert.ok(!createRetrievalScope(s).catalog().some(c=>c.path==='helper.ts'));});
test('extensionless imports resolve separately on old and new trees without cross-side ambiguity',async t=>{const {root,git}=await repo(t);await writeFile(path.join(root,'main.ts'),'import x from "./helper";\nexport default x;\n');await writeFile(path.join(root,'helper.ts'),'export default 1;\n');await git('add','.');await git('commit','-qm','base');await git('rm','helper.ts');await writeFile(path.join(root,'helper.js'),'export default 2;\n');await writeFile(path.join(root,'main.ts'),'import x from "./helper";\nexport default x+1;\n');await git('add','.');await git('commit','-qm','target');const before=await git('status','--porcelain');const s=await captureSnapshot(root,{commit:'HEAD',autoContext:true});assert.equal(s.autoContext.candidates.find(c=>c.path==='helper.ts').status,'reused-changed-old');assert.deepEqual(s.autoContext.candidates.find(c=>c.path==='helper.ts').sourceSides,['old']);assert.deepEqual(s.context,[]);const r=createRetrievalScope(s),catalog=r.catalog();for(const [p,side,text] of [['helper.ts','old','export default 1;\n'],['helper.js','new','export default 2;\n']]){const c=catalog.find(c=>c.path===p&&c.side===side);assert.ok(c.fileId);assert.equal(r.read({id:c.id,start:1,count:1}).text,text);}assert.equal(s.id,(await captureSnapshot(root,{commit:'HEAD',autoContext:true})).id);assert.deepEqual(await git('status','--porcelain'),before);});
