import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {checked} from '../src/process.mjs';
import {captureSnapshot} from '../src/snapshot.mjs';
import {reviewSnapshot} from '../src/review.mjs';
import {approvedCallerBindings} from '../src/caller-binding-input.mjs';
import {callerCandidates} from '../src/caller-candidates.mjs';
import {preparePrimaryInput} from '../src/primary-input.mjs';
import {createRetrievalScope} from '../src/retrieval-scope.mjs';
const base='a'.repeat(40),target='b'.repeat(40),binding={imported:'run',local:'execute',importLine:1,callLine:2,declarationLine:1,declarationKind:'function',confidence:'conservative-syntax-only'};
const file={path:'dep.ts',rawStatus:'M',left:{text:'export function run() {}'},right:{text:'export function run() {}'}};
const input=()=>({history:{base,target},context:[{path:'app/a.ts',text:'new',revision:target,oldText:'old',oldRevision:base}],callerDiscovery:{candidates:['old','new'].map(side=>({fromPath:'app/a.ts',targetPath:'dep.ts',side,revision:side==='old'?base:target,bindings:[binding]}))}});
test('historical caller hints require exact side revision body and target existence',()=>{
 const both=approvedCallerBindings(input(),file);assert.deepEqual(both.map(c=>[c.side,c.contextSide,c.revision,c.targetRevision]),[['old','context-old',base,base],['new','context',target,target]]);
 const noOld=input();delete noOld.context[0].oldText;assert.deepEqual(approvedCallerBindings(noOld,file).map(c=>c.side),['new']);
 const onlyOld=input();delete onlyOld.context[0].text;delete onlyOld.context[0].revision;assert.deepEqual(approvedCallerBindings(onlyOld,file).map(c=>c.side),['old']);
 const wrong=input();wrong.context[0].oldRevision=target;wrong.context[0].revision=base;assert.deepEqual(approvedCallerBindings(wrong,file),[]);
 const forged=input();forged.callerDiscovery.candidates.forEach(c=>c.revision='c'.repeat(40));assert.deepEqual(approvedCallerBindings(forged,file),[]);
 assert.deepEqual(approvedCallerBindings(input(),{...file,rawStatus:'A'}).map(c=>c.side),['new']);
 assert.deepEqual(approvedCallerBindings(input(),{...file,rightExists:false}).map(c=>c.side),['old']);
 const noSide=input();noSide.callerDiscovery.candidates.forEach(c=>delete c.side);assert.deepEqual(approvedCallerBindings(noSide,file),[]);
});
test('optional historical caller annotations never block otherwise fitting windows',()=>{
 const old='export function run() {}\n'+Array.from({length:100},(_,i)=>'// '+i+' '+ 'x'.repeat(600)).join('\n'),now=old+'\n// changed';
 const f={id:'f',path:'dep.ts',rawStatus:'M',eligibility:'reviewable',properties:[],left:{text:old},right:{text:now}};
 const sources=Array.from({length:7},(_,i)=>({path:'app/c'+i+'.ts',text:"import { run } from '../dep.ts';\n"+Array(20).fill('run();').join('\n')}));
 const candidates=['old','new'].flatMap(side=>callerCandidates([{...f,right:side==='old'?f.left:f.right}],sources,['dep.ts']).candidates.map(c=>({...c,side,revision:side==='old'?base:target})));
 assert.equal(candidates.reduce((n,c)=>n+c.bindings.length,0),280);
 const s={id:'s',vcs:'git',history:{base,target},files:[f],context:sources.map(c=>({...c,revision:target,oldText:c.text,oldRevision:base})),callerDiscovery:{candidates}};
 const options={instructions:'Review only approved evidence',scope:createRetrievalScope(s),maxInputBytes:98304};
 const prepared=preparePrimaryInput(s,f,options),baseline=preparePrimaryInput({...s,callerDiscovery:undefined},f,options);
 assert.equal(baseline.budget.fits,true);assert.equal(prepared.budget.fits,true);assert.equal(prepared.metadata.callerBindingFallback,'input-budget');assert.equal(prepared.metadata.omittedCallerBindingCount,280);
 assert.equal(JSON.parse(prepared.payload).callerBindings,undefined);assert.equal(prepared.payload,baseline.payload);
 assert.equal(s.callerDiscovery.candidates.length,14);assert.equal(s.context.length,7);
});
test('real Git historical changed declarations and deleted targets preserve distinct version lines',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-history-caller-binding-'));
 t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-history-caller-binding-'));await rm(root,{recursive:true,force:true});});
 const git=(...a)=>checked('git',a,{cwd:root});await git('init');await git('config','user.name','t');await git('config','user.email','a@b.c');await mkdir(path.join(root,'app'));
 await writeFile(path.join(root,'dep.ts'),'export function run() {}');
 await writeFile(path.join(root,'gone.ts'),'export function gone() {}');
 await writeFile(path.join(root,'app/a.ts'),"import { run as execute } from '../dep.ts';\nexecute();");
 await writeFile(path.join(root,'app/deleted.ts'),"import { gone } from '../gone.ts';\ngone();");
 await git('add','.');await git('commit','-qm','base');
 await writeFile(path.join(root,'dep.ts'),'\n\nexport function run() {}');
 await git('rm','gone.ts');await git('commit','-qam','target');
 await writeFile(path.join(root,'app/a.ts'),'DIRTY_WORKTREE_NOT_APPROVED');
 const s=await captureSnapshot(root,{commit:'HEAD',selectedPaths:['dep.ts','gone.ts'],callerScopePaths:['app']});
 const dep=s.callerDiscovery.candidates.filter(c=>c.targetPath==='dep.ts');assert.deepEqual(dep.map(c=>[c.side,c.bindings[0].declarationLine]),[['old',1],['new',3]]);
 const gone=s.callerDiscovery.candidates.filter(c=>c.targetPath==='gone.ts');assert.equal(gone.length,1);assert.equal(gone[0].side,'old');assert.equal(gone[0].bindings[0].declarationLine,1);
 assert.equal(s.context.find(c=>c.path==='app/deleted.ts').oldRevision,s.history.base);
 assert.ok(!JSON.stringify(s).includes('DIRTY_WORKTREE_NOT_APPROVED'));
 let calls=0;await reviewSnapshot(s,async r=>{const p=JSON.parse(r.input);calls++;if(p.file.path==='dep.ts')assert.deepEqual(p.callerBindings.map(c=>[c.side,c.bindings[0].declarationLine]),[['old',1],['new',3]]);else {assert.equal(p.file.path,'gone.ts');assert.equal(p.callerBindings.length,1);assert.equal(p.callerBindings[0].contextSide,'context-old');assert.equal(p.callerBindings[0].revision,s.history.base);}return {findings:[],limitations:[]};});assert.equal(calls,2);
});
