import {createReviewService} from '../src/service.mjs';
import {captureSnapshot} from '../src/snapshot.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {checked} from '../src/process.mjs';
import {captureGitHistory} from '../src/git-history.mjs';
import {createRetrievalScope} from '../src/retrieval-scope.mjs';
test('explicit baseline capture object-only and changed deletion remains changed identity',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-old-context-'));
 t.after(async()=>{assert.ok(path.basename(root).startsWith('dsh-old-context-'));await rm(root,{recursive:true,force:true});});
 const git=(...args)=>checked('git',args,{cwd:root});
 await git('init');await git('config','user.name','test');await git('config','user.email','test@example.com');
 await writeFile(path.join(root,'helper.ts'),'baseline helper');await writeFile(path.join(root,'a.ts'),'old a');await writeFile(path.join(root,'gone.ts'),'gone');
 await git('add','.');
 const linkOid=(await git('hash-object','-w','helper.ts')).toString().trim();
 await git('update-index','--add','--cacheinfo','120000',linkOid,'link.ts');
 await git('commit','-m','base');const base=(await git('rev-parse','HEAD')).toString().trim();
 await writeFile(path.join(root,'a.ts'),'new a');await git('rm','gone.ts');await git('add','a.ts');await git('commit','-m','target');const target=(await git('rev-parse','HEAD')).toString().trim();
 await writeFile(path.join(root,'helper.ts'),'WORKTREE NEVER READ');const before=await git('status','--porcelain');
 const opts={commit:target,oldContextPaths:['helper.ts','gone.ts']};const s=await captureGitHistory(root,opts);
 assert.equal(s.context.length,1);assert.equal(s.context[0].oldRevision,base);assert.equal(s.context[0].text,undefined);assert.equal(s.context[0].oldText,'baseline helper');
 assert.equal(s.id,(await captureGitHistory(root,opts)).id);assert.ok(createRetrievalScope(s).catalog().some(c=>c.path==='helper.ts'&&c.side==='context-old'));
 assert.deepEqual(await git('status','--porcelain'),before);
 let calls=0;const service=createReviewService({async *stream(request){calls++;assert.ok(!JSON.stringify(request).includes('WORKTREE NEVER READ'));assert.ok(JSON.stringify(request).includes('oldOnly:true'));yield {type:'text-delta',text:JSON.stringify({findings:[],limitations:[]})};yield {type:'finish',reason:{kind:'stop'}};}},{allowModelSending:true,authorize:async()=>true});
 const exec={agent:{session:{header:{cwd:root}},options:{provider:'offline',model:'none'}},signal:new AbortController().signal};
 const preview=await service.preview(opts,exec);assert.equal(calls,0);assert.equal(preview.oldContextSources[0].revision,base);assert.ok(!JSON.stringify(preview).includes('baseline helper'));
 const result=await service.execute({previewId:preview.previewId,confirmed:true},exec);assert.equal(result.report.outdated,false);assert.ok(calls>0);service.dispose();
 await assert.rejects(captureSnapshot(root,{oldContextPaths:[]}),/historical review/);
 await assert.rejects(captureGitHistory(root,{...opts,selectedPaths:['a.ts']}),/conflicts/);
 await assert.rejects(captureGitHistory(root,{commit:base,oldContextPaths:['helper.ts']}),/baseline/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['missing.ts']}),/regular blob/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['link.ts']}),/regular blob/);
 await git('update-index','--add','--cacheinfo','160000',base,'module');await git('commit','-m','submodule fixture');
 const moduleBase=(await git('rev-parse','HEAD')).toString().trim();
 await git('commit','--allow-empty','-m','module target');
 const moduleTarget=(await git('rev-parse','HEAD')).toString().trim();
 await assert.rejects(captureGitHistory(root,{baseRevision:moduleBase,targetRevision:moduleTarget,oldContextPaths:['module']}),/regular blob/);
 await assert.rejects(captureGitHistory(root,{commit:target,contextPaths:['helper.ts'],oldContextPaths:['helper.ts']}),/separate/);
 await assert.rejects(captureGitHistory(root,{...opts,maxContextFiles:1}),/limit/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['helper.ts','helper.ts']}),/Invalid/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['helper.ts'],maxFileBytes:5}),/limit/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['helper.ts'],maxSnapshotBytes:100}),/limit/);
 await assert.rejects(captureGitHistory(root,{commit:target,oldContextPaths:['.env']}),/Credential/);
});
