import {createReviewService} from '../src/service.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewSnapshot,REVIEW_INSTRUCTIONS} from '../src/review.mjs';
import {createRetrievalScope} from '../src/retrieval-scope.mjs';
import {buildCoveragePlan} from '../src/coverage-plan.mjs';
const s={id:'s',vcs:'git',context:[],files:[{id:'f',path:'a.txt',eligibility:'reviewable',properties:[],left:{text:'old'},right:{text:'new'}}]};
test('two independent passes strip first plan and share preview counts',async()=>{let calls=0;const r=await reviewSnapshot(s,req=>{calls++;const p=JSON.parse(req.input);if(calls===1)return {risks:[]};assert.equal(Object.hasOwn(p,'riskPlan'),calls===2);return {findings:[],limitations:[]};},{reviewRounds:2,enableRiskPlanning:true});const p=buildCoveragePlan(s,{reviewRounds:2,enableRiskPlanning:true,instructions:REVIEW_INSTRUCTIONS,maxInputBytes:96000});assert.equal(p.minimumCalls,3);assert.equal(r.modelCalls,3);assert.ok(r.files[0].reviewPasses.every(x=>x.status==='completed'));assert.equal(r.coverage.completed,1);});
test('call cap retains completed first pass but does not claim second or file completion',async()=>{const r=await reviewSnapshot(s,()=>({findings:[],limitations:[]}),{reviewRounds:2,maxCalls:1});assert.equal(r.modelCalls,1);assert.equal(r.files[0].reviewPasses[0].status,'completed');assert.equal(r.files[0].reviewPasses[1].status,'pending');assert.equal(r.coverage.completed,0);});
test('interaction passes share budget and cannot claim all rounds after first only',async()=>{
 const input={...s,files:[...s.files,{...s.files[0],id:'g',path:'b.txt'}]},options={reviewRounds:2,enableRetrieval:true,enableBusinessGrouping:true};
 const p=buildCoveragePlan(input,{...options,instructions:REVIEW_INSTRUCTIONS,scope:createRetrievalScope(input),maxInputBytes:96000});const model=()=>({findings:[],limitations:[]});const r=await reviewSnapshot(input,model,options);assert.equal(p.minimumCalls,6);assert.equal(r.modelCalls,6);assert.equal(r.interactions[0].status,'completed');assert.deepEqual(r.interactions[0].completedRounds,[1,2]);
 const capped=await reviewSnapshot(input,model,{...options,maxCalls:5});assert.equal(capped.interactions[0].status,'pending');assert.deepEqual(capped.interactions[0].completedRounds,[1]);assert.equal(capped.status,'partial');assert.equal(capped.files[1].reviewPasses.at(-1).status,'pending');
});
test('second pass timeout shares lifecycle and retains prior findings without completion',async()=>{let calls=0,cleaned=false;const r=await reviewSnapshot(s,async req=>{if(++calls===1)return {findings:[],limitations:[]};await new Promise(resolve=>req.signal.addEventListener('abort',resolve,{once:true}));cleaned=true;throw req.signal.reason;},{reviewRounds:2,timeoutMs:25});assert.equal(cleaned,true);assert.equal(r.files[0].reviewPasses[0].status,'completed');assert.equal(r.files[0].reviewPasses[1].status,'failed');assert.equal(r.coverage.completed,0);assert.equal(r.files[0].failureCode,'MODEL_TIMEOUT');});
test('each pass verifies its own candidate and preserves independent round provenance',async()=>{let mains=0;const r=await reviewSnapshot(s,req=>{const p=JSON.parse(req.input);if(p.candidates)return {verdicts:[{candidateId:'c1',verdict:'uncertain',reason:'missing caller',evidence:[]}]};mains++;assert.ok(!p.candidates&&!p.riskPlan);return {findings:[{fileId:'f',severity:'high',title:'candidate',evidence:'hypothesis',trigger:'unknown caller',impact:'failure',suggestion:'inspect',anchor:{kind:'file'}}],limitations:[]};},{reviewRounds:3,enableRetrieval:true,enableVerification:true});assert.equal(mains,3);assert.equal(r.modelCalls,6);assert.deepEqual(r.findings.map(f=>f.reviewRound),[1,2,3]);assert.ok(r.findings.every(f=>f.verification.verdict==='uncertain'));assert.equal(r.status,'partial');});
test('cancellation in second pass leaves next file pending or cancelled with no extra send',async()=>{const controller=new AbortController();let calls=0;const input={...s,files:[...s.files,{...s.files[0],id:'g',path:'b.txt'}]};const r=await reviewSnapshot(input,()=>{if(++calls===2)controller.abort(Error('stop'));return {findings:[],limitations:[]};},{reviewRounds:2,signal:controller.signal});assert.equal(calls,2);assert.equal(r.status,'cancelled');assert.equal(r.coverage.completed,0);assert.equal(r.files[0].reviewPasses[1].status,'cancelled');});
test('multiple windows and synthesis repeat independently without duplicating original window coverage',async()=>{
 const input=structuredClone(s),lines=Array.from({length:100},(_,i)=>'line'+i+'x'.repeat(200));input.files[0].left.text=lines.join('\n');const now=[...lines];now[10]='changed10';now[80]='changed80';input.files[0].right.text=now.join('\n');const options={reviewRounds:2,enableRetrieval:true,maxInputBytes:8000};
 const p=buildCoveragePlan(input,{...options,instructions:REVIEW_INSTRUCTIONS,scope:createRetrievalScope(input)});let firstSignal;const r=await reviewSnapshot(input,req=>{firstSignal??=req.signal;assert.equal(firstSignal,req.signal);return {findings:[],limitations:[]};},options);assert.equal(p.minimumCalls,6);assert.equal(r.modelCalls,6);assert.equal(r.files[0].windowCoverage.completed.length,2);assert.equal(r.files[0].reviewPasses.length,6);assert.equal(r.files[0].reviewPasses.filter(x=>x.synthesis&&x.status==='completed').length,2);
 const capped=await reviewSnapshot(input,()=>({findings:[],limitations:[]}),{...options,maxCalls:4});assert.equal(capped.coverage.completed,0);assert.equal(capped.files[0].windowCoverage.completed.length,2);assert.equal(capped.files[0].reviewPasses.filter(x=>x.status==='pending').length,2);
});
test('service explicitly previews configured rounds and executes without extra authorization',async()=>{let sends=0,authorizations=0;const service=createReviewService({async *stream(){sends++;yield {type:'text-delta',text:'{"findings":[],"limitations":[]}'};yield {type:'finish',reason:{kind:'stop'}};}},{capture:async()=>({...s,root:'/repo'}),reviewRounds:2,allowModelSending:true,authorize:async()=>{authorizations++;return true;}});const exec={agent:{session:{header:{cwd:'/repo'}},options:{provider:'test',model:'model'}},signal:new AbortController().signal};const p=await service.preview({},exec);assert.equal(p.plan.reviewRounds,2);assert.equal(p.plan.minimumCalls,2);assert.equal(sends,0);const r=await service.execute({previewId:p.previewId,confirmed:true},exec);assert.equal(sends,2);assert.equal(authorizations,1);assert.equal(r.report.coverage.completed,1);assert.match(r.markdown,/独立审查轮次/);
});
test('invalid work quantity rejected before sends',async()=>{for(const value of [0,4,1.5,'2'])await assert.rejects(()=>reviewSnapshot(s,()=>assert.fail('send'),{reviewRounds:value}));});
