import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { checked } from '../src/process.mjs';
import { captureSnapshot } from '../src/snapshot.mjs';
test('explicit context is captured, hashed and constrained', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'dsh-review-context-'));
  t.after(async () => { assert.ok(path.basename(root).startsWith('dsh-review-context-')); await rm(root, { recursive: true, force: true }); });
  const git = (...args) => checked('git', args, { cwd: root });
  await git('init', '-q'); await git('config', 'user.name', 'Test'); await git('config', 'user.email', 'test@example.invalid');
  await writeFile(path.join(root, 'a.js'), 'old'); await writeFile(path.join(root, 'context.js'), 'context');
  await git('add', '.'); await git('commit', '-qm', 'fixture'); await writeFile(path.join(root, 'a.js'), 'new');
  const snapshot = await captureSnapshot(root, { contextPaths: ['context.js'] });
  assert.equal(snapshot.vcs, 'git'); assert.equal(snapshot.context[0].text, 'context');
  assert.equal(snapshot.id, (await captureSnapshot(root, { contextPaths: ['context.js'] })).id);
  await assert.rejects(captureSnapshot(root, { contextPaths: ['../secret'] }), /Unsafe/);
  await assert.rejects(captureSnapshot(root, { maxSnapshotBytes: 10 }), /size limit/);
  await assert.rejects(captureSnapshot(root, { maxSnapshotBytes: NaN }), /Invalid snapshot limit/);
  await writeFile(path.join(root, 'rules.md'), 'Check resource ownership');
  await assert.rejects(captureSnapshot(root, { rulePaths: ['rules.md'] }), /excluded/);
  const selectedRule = await captureSnapshot(root, { rulePaths: ['rules.md'], selectedPaths: ['a.js', 'rules.md'] });
  assert.equal(selectedRule.rules[0].text, 'Check resource ownership');
  assert.equal(selectedRule.files.find(f => f.path === 'rules.md').eligibility, 'reviewable');
  await git('add', 'rules.md'); await git('commit', '-qm', 'rules fixture');
  const withRules = await captureSnapshot(root, { rulePaths: ['rules.md'] });
  assert.equal(withRules.rules[0].text, 'Check resource ownership');
  assert.notEqual(withRules.id, (await captureSnapshot(root)).id);
  assert.equal(withRules.id, (await captureSnapshot(root, { rulePaths: ['rules.md'] })).id);
  await writeFile(path.join(root, 'rules.md'), 'Check cancellation');
  assert.notEqual(withRules.id, (await captureSnapshot(root, { rulePaths: ['rules.md'] })).id);
  await assert.rejects(captureSnapshot(root, { rulePaths: ['rules.md'], contextPaths: ['rules.md'] }), /separate/);
  await assert.rejects(captureSnapshot(root, { rulePaths: ['rules.md'], maxSnapshotBytes: 10 }), /size limit/);
  await rm(path.join(root, 'a.js'));
  await assert.rejects(captureSnapshot(root, { contextPaths: ['a.js'] }), /Deleted path/);
});
