import {createReviewService} from '../src/service.mjs';
import {captureSvnDependencyChain} from '../src/svn-dependency-chain.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {checked} from '../src/process.mjs';import {captureSnapshot} from '../src/snapshot.mjs';
async function fixture(fn){const base=await mkdtemp(path.join(os.tmpdir(),'dsh-svn-chain-'));try{await checked('svnadmin',['create',path.join(base,'repo')]);const root=path.join(base,'wc');await checked('svn',['checkout','--non-interactive',pathToFileURL(path.join(base,'repo')).href,root]);const svn=(...a)=>checked('svn',['--non-interactive',...a],{cwd:root}),put=(n,t)=>writeFile(path.join(root,n),t);for(const [n,v] of [['main.ts','import {x} from "./barrel";'],['barrel.ts','export {x} from "./impl";'],['impl.ts','export {x} from "./end";'],['end.ts','export {x} from "./beyond";'],['beyond.ts','export const x=1;']])await put(n,v);await svn('add','--','main.ts@','barrel.ts@','impl.ts@','end.ts@','beyond.ts@');await svn('commit','-m','base');await put('main.ts','import {x} from "./barrel";'+String.fromCharCode(10)+'x();');await fn({root,svn,put});}finally{assert.ok(path.basename(base).startsWith('dsh-svn-chain-'));await rm(base,{recursive:true,force:true});}}
test('SVN exact normal nodes capture three dependency layers and stable identity',()=>fixture(async({root})=>{const s=await captureSnapshot(root,{autoContext:true});assert.deepEqual(s.context.map(c=>c.path),['barrel.ts','impl.ts','end.ts']);assert.equal(s.autoContext.truncated,true);assert.ok(!s.context.some(c=>c.path==='beyond.ts'));assert.equal(s.id,(await captureSnapshot(root,{autoContext:true})).id);}));
test('SVN chain preserves slots and refuses untracked extension competitors',()=>fixture(async({root,put})=>{const s=await captureSnapshot(root,{autoContext:true,maxContextFiles:1});assert.equal(s.context.length,1);assert.equal(s.autoContext.candidates[1].status,'blocked');await put('barrel.js','export const hidden=2;');const competing=await captureSnapshot(root,{autoContext:true});assert.equal(competing.context.length,0);}));
test('SVN explicit seeds share slots and committed cycles do not duplicate',()=>fixture(async({root,svn,put})=>{
 await put('impl.ts','export {x} from "./barrel";');await svn('commit','-m','cycle','--','impl.ts@');const s=await captureSnapshot(root,{autoContext:true,contextPaths:['impl.ts']});assert.deepEqual(s.context.map(c=>c.path),['barrel.ts','impl.ts']);assert.equal(s.autoContext.truncated,false);assert.equal(s.autoContext.sourceBytes,s.context.reduce((n,c)=>n+c.bytes,0));
 await assert.rejects(captureSvnDependencyChain(root,[],{contextPaths:['impl.ts'],signal:AbortSignal.abort()}));await assert.rejects(captureSvnDependencyChain(root,[],{contextPaths:['impl.ts','barrel.ts'],maxContextFiles:1}),/Context file limit/);
}));
test('SVN chain preview sends no source and stale terminal refuses before another model call',()=>fixture(async({root,put})=>{
 let sends=0;const exec={agent:{session:{header:{cwd:root}},options:{provider:'offline',model:'test'}},signal:new AbortController().signal};const service=createReviewService({async *stream(req){sends++;const p=JSON.parse(req.messages[0].content[0].text);assert.ok(p.catalog.some(c=>c.path==='end.ts'));assert.ok(!p.catalog.some(c=>c.path==='beyond.ts'));yield {type:'text-delta',text:'{"findings":[],"limitations":[]}'};yield {type:'finish',reason:{kind:'stop'}};}},{allowModelSending:true,authorize:async()=>true});
 const p=await service.preview({autoContext:true},exec);assert.equal(sends,0);assert.ok(!JSON.stringify(p).includes('export {x}'));await service.execute({previewId:p.previewId,confirmed:true},exec);assert.equal(sends,1);const next=await service.preview({autoContext:true},exec);await put('end.ts','export const changed=3;');await assert.rejects(service.execute({previewId:next.previewId,confirmed:true},exec),/changed|outdated/i);assert.equal(sends,1);
}));
test('SVN exact probes are bounded before filesystem lookup and untracked sole dependency grants no body',()=>fixture(async({root,put})=>{
 const files=[{path:'main.ts',eligibility:'reviewable',right:{text:Array.from({length:40},(_,i)=>'import x from "./d'+i+'";').join(String.fromCharCode(10))}}];await assert.rejects(captureSvnDependencyChain(root,files),/lookup limit/);await put('untracked.ts','SECRET BODY');const chain=await captureSvnDependencyChain(root,[{path:'main.ts',eligibility:'reviewable',right:{text:'import x from "./untracked.ts";'}}]);assert.equal(chain.context.length,0);assert.equal(chain.autoContext.candidates[0].status,'blocked');
}));
test('SVN dependency final verification rejects property identity changes',()=>fixture(async({root,svn})=>{
 const chain=await captureSvnDependencyChain(root,[{path:'main.ts',eligibility:'reviewable',right:{text:'import {x} from "./barrel";'}}]);await svn('propset','custom:test','changed','--','end.ts@');await assert.rejects(chain.verify(),/state|changed|properties/i);
}));
test('SVN chain blocks keyword-bearing dependencies before reading bodies',()=>fixture(async({root,svn})=>{await svn('propset','svn:keywords','Id','--','barrel.ts@');await svn('commit','-m','keywords','--','barrel.ts@');const s=await captureSnapshot(root,{autoContext:true});assert.equal(s.context.length,0);assert.equal(s.autoContext.candidates[0].status,'blocked');assert.match(s.autoContext.candidates[0].reason,/properties/);}));
