import assert from 'node:assert/strict';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import * as plugin from '../index.mjs';
const host = process.argv[2];
if (!host) throw new Error('Pass the installed DSH checkout path');
const load = name => import(pathToFileURL(path.join(host, 'node_modules/@deepseek-ai', name, 'lib/index.js')).href);
const { Context } = await load('cordis');
const { default: Tools } = await load('dsh-tools');
console.log('ToolRuntime required services:', Tools.inject);
const ctx = new Context();
console.log('Cordis context loaded; plugin metadata:', plugin.name, plugin.inject);
assert.equal(typeof Tools, 'function');
ctx.provide('systemPrompt');
ctx.provide('llm');
ctx.provide('approval');
ctx.set('systemPrompt', { tools() {}, section() {}, getSectionOrder() { return 0; } });
const tools = new Tools(ctx, { mode: 'native' });
ctx.set('llm', { stream() { throw new Error('Network disabled in host smoke'); } });
ctx.set('approval', { request: async () => 'rejected' });
plugin.apply(ctx, { allowModelSending: false });
console.log('Real ToolRuntime accepted both plugin definitions.');
