import assert from 'node:assert/strict';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import * as plugin from '../index.mjs';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import { checked } from '../src/process.mjs';
const host = process.argv[2];
if (!host) throw new Error('Pass the installed DSH checkout path');
const load = name => import(pathToFileURL(path.join(host, 'node_modules/@deepseek-ai', name, 'lib/index.js')).href);
const boot = await load('dsh-app-boot');
const packageDir = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const manifest = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
const patches = boot.bundlePatchPaths(packageDir, manifest.dsh.bundle).map(file => boot.loadOverlayPatches('dsh', file));
const entries = boot.composeEntries(patches);
assert.equal(entries.length, 1);
assert.equal(entries[0].name, manifest.name);
assert.deepEqual(entries[0].config, {});
console.log('Host bundle parser accepted safe-default composition.');
const display = boot.readPluginMeta(manifest.name, new URL('../index.mjs', import.meta.url).href);
assert.equal(display?.error, undefined);
assert.equal(display?.title?.['zh-cn'], '代码审查');
assert.equal(display?.title?.en, 'Code Review');
console.log('Host metadata resolver accepted localized plugin display titles.');
const { Context } = await load('cordis');
const { default: Tools } = await load('dsh-tools');
console.log('ToolRuntime required services:', Tools.inject);
const ctx = new Context();
console.log('Cordis context loaded; plugin metadata:', plugin.name, plugin.inject);
assert.equal(typeof Tools, 'function');
ctx.provide('systemPrompt');
ctx.provide('llm');
ctx.provide('approval');
ctx.set('systemPrompt', { tools() {}, section() {}, getSectionOrder() { return 0; } });
const tools = new Tools(ctx, { mode: 'native' });
let allowed = false, modelCalls = 0, approvalCalls = 0;
ctx.set('llm', { async *stream(request) {
  assert.ok(allowed); modelCalls++;
  assert.equal(request.provider, 'offline-test');
  assert.equal(request.model, 'none');
  assert.deepEqual(request.tools, []);
  yield { type: 'text-delta', text: JSON.stringify(request.system.includes('仅制定审查计划') ? { risks: [] } : { findings: [], limitations: [] }) };
  yield { type: 'finish', reason: { kind: 'stop' } };
} });
ctx.set('approval', { request: async request => {
  approvalCalls++;
  assert.match(request.reason, /offline-test\/none/);
  return allowed ? 'allowed-once' : 'rejected';
} });
plugin.apply(ctx, { allowModelSending: true });
console.log('Real ToolRuntime accepted both plugin definitions.');
const root = await mkdtemp(path.join(os.tmpdir(), 'dsh-review-host-'));
try {
  await checked('git', ['init', '-q'], { cwd: root });
  await writeFile(path.join(root, 'sample.js'), 'const value = 1;');
  await checked('git', ['add', 'sample.js'], { cwd: root });
  const exec = { agent: { session: { header: { cwd: root } }, options: { provider: 'offline-test', model: 'none' } }, signal: new AbortController().signal };
  const previewTool = tools.get('code_review_preview');
  assert.ok(previewTool);
  const preview = JSON.parse((await previewTool.execute({}, exec)).json);
  assert.equal(preview.files.length, 1);
  assert.equal(preview.files[0].eligibility, 'reviewable');
  await assert.rejects(tools.get('code_review_execute').execute({ previewId: preview.previewId, confirmed: false }, exec), /confirm/i);
  assert.equal(modelCalls, 0);
  console.log('Registered tool preview captured real Git content; unconfirmed execution prevented LLM execution.');
  allowed = true;
  const approvedPreview = JSON.parse((await previewTool.execute({}, exec)).json);
  const statusBefore = await checked('git', ['status', '--porcelain=v1'], { cwd: root });
  const output = await tools.get('code_review_execute').execute({ previewId: approvedPreview.previewId, confirmed: true }, exec);
  const report = JSON.parse(output.json);
  assert.equal(modelCalls, 1); assert.equal(approvedPreview.plan.minimumCalls, 1); assert.equal(report.files[0].riskPlans[0].status, 'skipped'); assert.equal(approvalCalls, 0);
  assert.equal(report.coverage.completed, 1);
  assert.equal(report.outdated, false);
  assert.equal(report.model.provider, 'offline-test');
  assert.match(output.markdown, /Code Review/);
  assert.deepEqual(await checked('git', ['status', '--porcelain=v1'], { cwd: root }), statusBefore);
  assert.equal(await readFile(path.join(root, 'sample.js'), 'utf8'), 'const value = 1;');
  const roundsPreview=JSON.parse((await previewTool.execute({reviewRounds:2},exec)).json);
  assert.equal(roundsPreview.plan.reviewRounds,2);assert.equal(roundsPreview.plan.minimumCalls,2);
  const twice=JSON.parse((await tools.get('code_review_execute').execute({previewId:roundsPreview.previewId,confirmed:true},exec)).json);
  assert.equal(modelCalls,3);assert.equal(twice.files[0].reviewPasses.length,2);assert.ok(twice.files[0].reviewPasses.every(p=>p.status==='completed'));assert.equal(approvalCalls,0);
  assert.deepEqual(await checked('git',['status','--porcelain=v1'],{cwd:root}),statusBefore);
  await checked('git',['config','user.name','test'],{cwd:root});await checked('git',['config','user.email','test@example.com'],{cwd:root});
  await checked('git',['commit','-qm','base'],{cwd:root});
  await writeFile(path.join(root,'sample.js'),'const value = 2;');await checked('git',['commit','-qam','target'],{cwd:root});
  const historical=JSON.parse((await previewTool.execute({commit:'HEAD',callerScopePaths:['clients']},exec)).json);assert.ok(historical.callerDiscovery);assert.equal(historical.callerDiscovery.indexes.length,2);
  const beforeHistory=await checked('git',['status','--porcelain=v1'],{cwd:root});
  const historyReport=JSON.parse((await tools.get('code_review_execute').execute({previewId:historical.previewId,confirmed:true},exec)).json);assert.equal(historyReport.coverage.completed,1);assert.equal(historyReport.outdated,false);assert.equal(modelCalls,4);assert.equal(approvalCalls,0);assert.deepEqual(await checked('git',['status','--porcelain=v1'],{cwd:root}),beforeHistory);
  console.log('Host-invoked offline adapter completed single and explicit double review without additional approval via current Agent route without modifying Git content.');
} finally {
  assert.ok(path.basename(root).startsWith('dsh-review-host-'));
  await rm(root, { recursive: true, force: true });
}
